printWidth: 100
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
filepath: none
requirePragma: false
insertPragma: false
proseWrap: preserve
endOfLine: crlf
embeddedLanguageFormatting: auto
